### PR TITLE
tweak stuff to work with latest laravel in blade and bootstrap 4

### PR DESCRIPTION
**Pull request by rjacobsen2012**
I fixed some minor spelling issues, made it work with bootstrap 4, and did some style tweaks for anyone who wants to use it.

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]
Can you please add new line at each file where the workflow is complaining about?
Also, did you test the samples commands and make sure they generate properly? 


It would be nice to see a PR adding support with Bootstrap 5.3.

**Comment by rjacobsen2012** [comment]
> Can you please add new line at each file where the workflow is complaining about? Also, did you test the samples commands and make sure they generate properly?
> 
> It would be nice to see a PR adding support with Bootstrap 5.3.

I am not a huge fan of Bootstrap 5.3 since they removed a bunch of stuff everyone was using with no backwards compatibility. I ran the samples locally, and they worked. Where are you seeing the new line errors?

**Comment by rjacobsen2012** [comment]
> Can you please add new line at each file where the workflow is complaining about? Also, did you test the samples commands and make sure they generate properly?
> 
> It would be nice to see a PR adding support with Bootstrap 5.3.

Also, there seems to be a bug when adding the route names that adds an extra model name in the name. I looked to try to find and fix it, but not sure where you are doing that.

image

**Comment by MikeAlhayek** [comment]
I have not tested out your changes. Just want to ensure they are tested fully. 

Also, the same changes should made on the default theme should also be made on the collective theme as well.

Bootstrap 5.3 is pretty nice.

**Comment by rjacobsen2012** [comment]
> I have not tested out your changes. Just want to ensure they are tested fully.
> 
> Also, the same changes should made on the default theme should also be made on the collective theme as well.
> 
> Bootstrap 5.3 is pretty nice.

I may see if I can update to latest `Carbon` as well.
image

**Comment by MikeAlhayek** [comment]
I am going to close this PR. Sorry. master branch already contains template for Laravel 5.3 with theming support. In the next couple of days I am planning to release 3.0

**Pull request closed without merging**
